# Generated by Django 5.1.5 on 2025-01-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalaGononeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_it', models.CharField(max_length=1000)),
                ('title_en', models.CharField(max_length=1000)),
                ('description_it', models.CharField(max_length=10000)),
                ('description_en', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=1000, verbose_name='e-main')),
                ('address', models.CharField(max_length=1000, verbose_name='Via')),
                ('cap_and_town', models.CharField(max_length=1000, verbose_name='CAP e nome paese')),
                ('region_and_country_it', models.CharField(max_length=1000, verbose_name='Regione e stato (in italiano)')),
                ('region_and_country_en', models.CharField(max_length=1000, verbose_name='Regione e stato (in inglese)')),
                ('tassa_di_soggiorno_it', models.CharField(max_length=10000, verbose_name='Tassa di soggiorno (in italiano)')),
                ('tassa_di_soggiorno_en', models.CharField(max_length=10000, verbose_name='Tassa di soggiorno (in inglese)')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('italian', models.CharField(max_length=10000)),
                ('english', models.CharField(max_length=10000)),
            ],
        ),
    ]
