# Generated by Django 5.1.5 on 2025-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0002_alter_welcomeinfo_english_alter_welcomeinfo_italian'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomeinfo',
            name='background_img',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Home background image'),
        ),
        migrations.AlterField(
            model_name='calagononeinfo',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calagononeinfo',
            name='description_it',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='mail',
            field=models.CharField(max_length=1000, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='tassa_di_soggiorno_en',
            field=models.TextField(verbose_name='Tassa di soggiorno (in inglese)'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='tassa_di_soggiorno_it',
            field=models.TextField(verbose_name='Tassa di soggiorno (in italiano)'),
        ),
        migrations.AlterField(
            model_name='welcomeinfo',
            name='english',
            field=models.TextField(verbose_name='Descrizione in inglese'),
        ),
        migrations.AlterField(
            model_name='welcomeinfo',
            name='italian',
            field=models.TextField(verbose_name='Descrizione in italiano'),
        ),
    ]
