# Generated by Django 5.1.5 on 2025-01-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0003_welcomeinfo_background_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1, verbose_name='Numero Appartamento (1/2/3)')),
                ('name', models.CharField(max_length=1000, verbose_name='Nome Proprio Appartamento')),
                ('short_descr_it', models.TextField(verbose_name='Descrizione Breve (in italiano)')),
                ('short_descr_en', models.TextField(verbose_name='Descrizione Breve (in inglese)')),
                ('key_features_it', models.TextField(verbose_name='Caratteristiche Chiave (una linea per ciascuna) in italiano')),
                ('key_features_en', models.TextField(verbose_name='Caratteristiche Chiave (una linea per ciascuna) in italiano')),
                ('full_descr_it', models.TextField(verbose_name='Descrizione Completa (in italiano)')),
                ('full_descr_en', models.TextField(verbose_name='Descrizione Completa (in inglese)')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (opzionale)')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sito.apartment')),
            ],
        ),
    ]
