# Generated by Django 5.1.5 on 2025-01-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0004_apartment_apartmentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='index',
            field=models.IntegerField(default=1, unique=True, verbose_name='Numero Appartamento (1/2/3)'),
        ),
    ]
