# Generated by Django 5.1.5 on 2025-01-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0005_alter_apartment_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
        migrations.AddField(
            model_name='apartment',
            name='name_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Nome Appartamento (in inglese)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='name_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Nome Appartamento (in italiano)'),
        ),
    ]
