# Generated by Django 5.1.5 on 2025-01-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0006_remove_apartment_name_apartment_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='key_features_en',
            field=models.TextField(verbose_name='Caratteristiche Chiave (una linea per ciascuna) in inglese'),
        ),
    ]
