# Generated by Django 5.1.5 on 2025-01-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0007_alter_apartment_key_features_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_home_it', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina home (IT)')),
                ('page_title_home_en', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina home (EN)')),
                ('page_title_calagonone_it', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina calagonone (IT)')),
                ('page_title_calagonone_en', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina calagonone (EN)')),
                ('page_title_contacts_it', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina contacts (IT)')),
                ('page_title_contacts_en', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina contacts (EN)')),
                ('page_title_apartment_it', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina apartment (IT)')),
                ('page_title_apartment_en', models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina home (EN)')),
                ('section_home_it', models.CharField(default='', max_length=1000, verbose_name='Etichetta Sezione home (IT)')),
                ('section_home_en', models.CharField(default='', max_length=1000, verbose_name='Etichetta Sezione home (EN)')),
                ('section_calagonone_it', models.CharField(default='', max_length=1000, verbose_name='Etichetta Sezione calagonone (IT)')),
                ('section_calagonone_en', models.CharField(default='', max_length=1000, verbose_name='Etichetta Sezione calagonone (EN)')),
                ('section_contacts_it', models.CharField(default='', max_length=1000, verbose_name='Etichetta Sezione contacts (IT)')),
                ('section_contacts_en', models.CharField(default='', max_length=1000, verbose_name='Etichetta Sezione contacts (EN)')),
                ('view_apartments_it', models.CharField(default='', max_length=1000, verbose_name="Etichetta per 'guarda gli appartamenti' (IT)")),
                ('view_apartments_en', models.CharField(default='', max_length=1000, verbose_name="Etichetta per 'guarda gli appartamenti' (EN)")),
                ('book_it', models.CharField(default='', max_length=1000, verbose_name="Etichetta per 'prenota' (IT)")),
                ('book_en', models.CharField(default='', max_length=1000, verbose_name="Etichetta per 'prenota' (EN)")),
                ('details_it', models.CharField(default='', max_length=1000, verbose_name="Etichetta per 'dettagli appartamento' (IT)")),
                ('details_en', models.CharField(default='', max_length=1000, verbose_name="Etichetta per 'dettagli appartamento' (EN)")),
            ],
        ),
    ]
