# Generated by Django 5.1.5 on 2025-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0008_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='business_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Nome Residenza'),
        ),
        migrations.AddField(
            model_name='labels',
            name='page_title',
            field=models.CharField(default='', max_length=1000, verbose_name='Titolo Pagina Base'),
        ),
    ]
