# Generated by Django 5.1.5 on 2025-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0009_labels_business_name_labels_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='location_directions_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Etichetta Come Arrivare (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='location_directions_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Etichetta Come Arrivare (IT)'),
        ),
    ]
