# Generated by Django 5.1.5 on 2025-01-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0010_labels_location_directions_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsinfo',
            name='phone',
            field=models.CharField(default='', max_length=1000, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='labels',
            name='contacts_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Titolo sezione 'contatti' (info e contatti) (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='contacts_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Titolo sezione 'contatti' (info e contatti) (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='quick_book_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Titolo sezione 'prenota' (info e contatti) (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='quick_book_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Titolo sezione 'prenota' (info e contatti) (IT)"),
        ),
    ]
