# Generated by Django 5.1.5 on 2025-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0011_contactsinfo_phone_labels_contacts_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='phone_en',
            field=models.CharField(default='', max_length=1000, verbose_name="'telefono' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='phone_it',
            field=models.CharField(default='', max_length=1000, verbose_name="'telefono' (IT)"),
        ),
    ]
