# Generated by Django 5.1.5 on 2025-01-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0012_labels_phone_en_labels_phone_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='location_en',
            field=models.CharField(default='', max_length=1000, verbose_name="'residenza' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='location_it',
            field=models.CharField(default='', max_length=1000, verbose_name="'residenza' (IT)"),
        ),
    ]
