# Generated by Django 5.1.5 on 2025-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0013_labels_location_en_labels_location_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='call_en',
            field=models.CharField(default='', max_length=1000, verbose_name="'chiama' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='call_it',
            field=models.CharField(default='', max_length=1000, verbose_name="'chiama' (IT)"),
        ),
    ]
