# Generated by Django 5.1.5 on 2025-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0014_labels_call_en_labels_call_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='max_people',
            field=models.CharField(default='5', max_length=1000, verbose_name='Numero Massimo Persone'),
        ),
    ]
