# Generated by Django 5.1.5 on 2025-01-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0015_apartment_max_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='form_adults_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Adulti Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_adults_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Adulti Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_apartment_en',
            field=models.CharField(default='', max_length=1000, verbose_name="'scegli appartamento' Form (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_apartment_it',
            field=models.CharField(default='', max_length=1000, verbose_name="'scegli appartamento' Form (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_check_in',
            field=models.CharField(default='', max_length=1000, verbose_name='Check in Form'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_check_out',
            field=models.CharField(default='', max_length=1000, verbose_name='Check out Form'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_children_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Bambini Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_children_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Bambini Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_people_en',
            field=models.CharField(default='', max_length=1000, verbose_name="'Persone' Form (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_people_it',
            field=models.CharField(default='', max_length=1000, verbose_name="'Persone' Form (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_submit_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Invia Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_submit_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Invia Form (IT)'),
        ),
    ]
