# Generated by Django 5.1.5 on 2025-01-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0016_labels_form_adults_en_labels_form_adults_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='form_email_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Email Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_email_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Email Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_email_ph_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Placeholder Email Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_email_ph_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Placeholder Email Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_message_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Message Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_message_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Message Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_message_ph_en',
            field=models.CharField(default='', max_length=1000, verbose_name='PlaceholderMessage Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_message_ph_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Placeholder Message Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_phone_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Phone Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_phone_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Phone Form (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_phone_ph_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Placeholder Phone Form (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_phone_ph_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Placeholder Phone Form (IT)'),
        ),
    ]
