# Generated by Django 5.1.5 on 2025-02-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0017_labels_form_email_en_labels_form_email_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsinfo',
            name='cancelation_en',
            field=models.TextField(default='', verbose_name='Cancellazione (EN)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='cancelation_it',
            field=models.TextField(default='', verbose_name='Cancellazione (IT)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='prices_en',
            field=models.TextField(default='', verbose_name='Prezzi e condizioni (EN)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='prices_it',
            field=models.TextField(default='', verbose_name='Prezzi e condizioni (IT)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='privacy_en',
            field=models.TextField(default='', verbose_name='Privacy Policy (EN)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='privacy_it',
            field=models.TextField(default='', verbose_name='Privacy Policy (IT)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='rubbish_en',
            field=models.TextField(default='', verbose_name='Rifiuti (EN)'),
        ),
        migrations.AddField(
            model_name='contactsinfo',
            name='rubbish_it',
            field=models.TextField(default='', verbose_name='Rifiuti (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='cancelation_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'cancellazione' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='cancelation_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'cancellazione' (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='prices_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'prezzi e condizioni' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='prices_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'prezzi e condizioni' (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='rubbish_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'rifiuti' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='rubbish_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'rifiuti' (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='taxes_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'tasse' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='taxes_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'tasse' (IT)"),
        ),
    ]
