# Generated by Django 5.1.5 on 2025-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0018_contactsinfo_cancelation_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='full_descr_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'descrizione' appartamento (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='full_descr_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'descrizione' appartamento (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='in_evidenza_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'in evidenza' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='in_evidenza_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'in evidenza' (IT)"),
        ),
    ]
