# Generated by Django 5.1.5 on 2025-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0019_labels_full_descr_en_labels_full_descr_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='other_apartments_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'altri appartamenti' (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='other_apartments_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'altri appartamenti' (IT)"),
        ),
    ]
