# Generated by Django 5.1.5 on 2025-05-25 17:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0020_labels_other_apartments_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeinfo',
            name='background_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Background Image'),
        ),
    ]
