# Generated by Django 5.1.5 on 2025-05-25 18:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0021_alter_welcomeinfo_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Apartment Image'),
        ),
    ]
