# Generated by Django 6.0.3 on 2026-03-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0022_alter_apartmentimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='available',
            field=models.BooleanField(default=True, verbose_name="L'appartamento è affittabile (dovrebbe essere mostrato nel sito)?"),
        ),
    ]
