# Generated by Django 6.0.3 on 2026-03-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0023_apartment_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='apartment_not_available_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'appartamento non disponibile' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='apartment_not_available_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'appartamento non disponibile' (IT)"),
        ),
    ]
