# Generated by Django 6.0.3 on 2026-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0024_labels_apartment_not_available_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='where_are_we_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'Dove siamo' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='where_are_we_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'Dove siamo' (IT)"),
        ),
    ]
