# Generated by Django 6.0.3 on 2026-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0025_labels_where_are_we_en_labels_where_are_we_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='calagononeinfo',
            name='name_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
