# Generated by Django 6.0.3 on 2026-05-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0026_calagononeinfo_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='view_map_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'Accetta e visualizza' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='view_map_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'Accetta e visualizza' (IT)"),
        ),
        migrations.AlterField(
            model_name='calagononeinfo',
            name='name_id',
            field=models.CharField(default='', max_length=100, verbose_name='Identificativo speciale (non modificiare)'),
        ),
    ]
