# Generated by Django 6.0.3 on 2026-05-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0027_labels_view_map_en_labels_view_map_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='read_less_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'leggi meno' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='read_less_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'leggi meno' (IT)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='read_more_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'leggi di piu' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='read_more_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'leggi di piu' (IT)"),
        ),
    ]
