# Generated by Django 6.0.3 on 2026-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0028_labels_read_less_en_labels_read_less_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='gallery_en',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'Galleria' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='gallery_it',
            field=models.CharField(default='', max_length=1000, verbose_name="Etichetta 'Galleria' (IT)"),
        ),
    ]
