# Generated by Django 6.0.3 on 2026-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0029_labels_gallery_en_labels_gallery_it'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartmentimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='apartmentimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordine (automatico)'),
        ),
    ]
