# Generated by Django 6.0.3 on 2026-05-07 18:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0030_alter_apartmentimage_options_apartmentimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalaGononeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Cala Gonone Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (opzionale)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine (automatico)')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sito.calagononeinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
