# Generated by Django 6.0.3 on 2026-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0031_calagononeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='calagononeinfo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='calagononeinfo',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordine (1/2/3/4/...)'),
        ),
    ]
