# Generated by Django 6.0.3 on 2026-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0032_alter_apartment_options_alter_calagononeinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calagononeimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (EN)'),
        ),
        migrations.AlterField(
            model_name='calagononeimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (IT)'),
        ),
    ]
