# Generated by Django 6.0.3 on 2026-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0033_calagononeimage_caption_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (EN)'),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (IT)'),
        ),
    ]
