# Generated by Django 6.0.3 on 2026-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0034_apartmentimage_caption_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_color', models.CharField(default='purple-600', max_length=100, verbose_name='Colore secondario (di bottoni e altro)')),
            ],
        ),
    ]
