# Generated by Django 6.0.3 on 2026-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0035_moreconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreconfig',
            name='secondary_col_hover_bg',
            field=models.CharField(default='purple-700', max_length=100, verbose_name='Colore secondario più scuro (hover bg)'),
        ),
        migrations.AddField(
            model_name='moreconfig',
            name='secondary_col_hover_ring',
            field=models.CharField(default='purple-300', max_length=100, verbose_name='Colore secondario più chiaro (hover ring)'),
        ),
    ]
