# Generated by Django 6.0.3 on 2026-05-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0036_moreconfig_secondary_col_hover_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='home_gallery_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'Galleria residenza' (EN)"),
        ),
        migrations.AddField(
            model_name='labels',
            name='home_gallery_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'Galleria residenza' (IT)"),
        ),
    ]
