# Generated by Django 6.0.3 on 2026-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0037_labels_home_gallery_en_labels_home_gallery_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='max_people',
            field=models.CharField(default='5', max_length=10, verbose_name='Numero Massimo Persone'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Appartamento (in inglese)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name_it',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Appartamento (in italiano)'),
        ),
        migrations.AlterField(
            model_name='calagononeinfo',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calagononeinfo',
            name='title_it',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Via'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='cap_and_town',
            field=models.CharField(max_length=100, verbose_name='CAP e nome paese'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='mail',
            field=models.CharField(max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='region_and_country_en',
            field=models.CharField(max_length=100, verbose_name='Regione e stato (in inglese)'),
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='region_and_country_it',
            field=models.CharField(max_length=100, verbose_name='Regione e stato (in italiano)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='book_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'prenota' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='book_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'prenota' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='business_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Residenza'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='call_en',
            field=models.CharField(default='', max_length=100, verbose_name="'chiama' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='call_it',
            field=models.CharField(default='', max_length=100, verbose_name="'chiama' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='cancelation_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'cancellazione' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='cancelation_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'cancellazione' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='contacts_en',
            field=models.CharField(default='', max_length=100, verbose_name="Titolo sezione 'contatti' (info e contatti) (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='contacts_it',
            field=models.CharField(default='', max_length=100, verbose_name="Titolo sezione 'contatti' (info e contatti) (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='details_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'dettagli appartamento' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='details_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'dettagli appartamento' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_adults_en',
            field=models.CharField(default='', max_length=100, verbose_name='Adulti Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_adults_it',
            field=models.CharField(default='', max_length=100, verbose_name='Adulti Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_apartment_en',
            field=models.CharField(default='', max_length=100, verbose_name="'scegli appartamento' Form (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_apartment_it',
            field=models.CharField(default='', max_length=100, verbose_name="'scegli appartamento' Form (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_check_in',
            field=models.CharField(default='', max_length=100, verbose_name='Check in Form'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_check_out',
            field=models.CharField(default='', max_length=100, verbose_name='Check out Form'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_children_en',
            field=models.CharField(default='', max_length=100, verbose_name='Bambini Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_children_it',
            field=models.CharField(default='', max_length=100, verbose_name='Bambini Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_email_en',
            field=models.CharField(default='', max_length=100, verbose_name='Email Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_email_it',
            field=models.CharField(default='', max_length=100, verbose_name='Email Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_email_ph_en',
            field=models.CharField(default='', max_length=100, verbose_name='Placeholder Email Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_email_ph_it',
            field=models.CharField(default='', max_length=100, verbose_name='Placeholder Email Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_message_en',
            field=models.CharField(default='', max_length=100, verbose_name='Message Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_message_it',
            field=models.CharField(default='', max_length=100, verbose_name='Message Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_message_ph_en',
            field=models.CharField(default='', max_length=100, verbose_name='PlaceholderMessage Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_message_ph_it',
            field=models.CharField(default='', max_length=100, verbose_name='Placeholder Message Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_people_en',
            field=models.CharField(default='', max_length=100, verbose_name="'Persone' Form (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_people_it',
            field=models.CharField(default='', max_length=100, verbose_name="'Persone' Form (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_phone_en',
            field=models.CharField(default='', max_length=100, verbose_name='Phone Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_phone_it',
            field=models.CharField(default='', max_length=100, verbose_name='Phone Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_phone_ph_en',
            field=models.CharField(default='', max_length=100, verbose_name='Placeholder Phone Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_phone_ph_it',
            field=models.CharField(default='', max_length=100, verbose_name='Placeholder Phone Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_submit_en',
            field=models.CharField(default='', max_length=100, verbose_name='Invia Form (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_submit_it',
            field=models.CharField(default='', max_length=100, verbose_name='Invia Form (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='full_descr_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'descrizione' appartamento (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='full_descr_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'descrizione' appartamento (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='gallery_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'Galleria' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='gallery_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'Galleria' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='in_evidenza_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'in evidenza' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='in_evidenza_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'in evidenza' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='location_directions_en',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Come Arrivare (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='location_directions_it',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Come Arrivare (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='location_en',
            field=models.CharField(default='', max_length=100, verbose_name="'residenza' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='location_it',
            field=models.CharField(default='', max_length=100, verbose_name="'residenza' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='other_apartments_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'altri appartamenti' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='other_apartments_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'altri appartamenti' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina Base'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_apartment_en',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina home (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_apartment_it',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina apartment (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_calagonone_en',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina calagonone (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_calagonone_it',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina calagonone (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_contacts_en',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina contacts (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_contacts_it',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina contacts (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_home_en',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina home (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='page_title_home_it',
            field=models.CharField(default='', max_length=100, verbose_name='Titolo Pagina home (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='phone_en',
            field=models.CharField(default='', max_length=100, verbose_name="'telefono' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='phone_it',
            field=models.CharField(default='', max_length=100, verbose_name="'telefono' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='prices_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'prezzi e condizioni' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='prices_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'prezzi e condizioni' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='quick_book_en',
            field=models.CharField(default='', max_length=100, verbose_name="Titolo sezione 'prenota' (info e contatti) (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='quick_book_it',
            field=models.CharField(default='', max_length=100, verbose_name="Titolo sezione 'prenota' (info e contatti) (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='read_less_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'leggi meno' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='read_less_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'leggi meno' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='read_more_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'leggi di piu' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='read_more_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'leggi di piu' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='rubbish_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'rifiuti' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='rubbish_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'rifiuti' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='section_calagonone_en',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Sezione calagonone (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='section_calagonone_it',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Sezione calagonone (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='section_contacts_en',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Sezione contacts (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='section_contacts_it',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Sezione contacts (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='section_home_en',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Sezione home (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='section_home_it',
            field=models.CharField(default='', max_length=100, verbose_name='Etichetta Sezione home (IT)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='taxes_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'tasse' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='taxes_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'tasse' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='view_apartments_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'guarda gli appartamenti' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='view_apartments_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta per 'guarda gli appartamenti' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='view_map_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'Accetta e visualizza' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='view_map_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'Accetta e visualizza' (IT)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='where_are_we_en',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'Dove siamo' (EN)"),
        ),
        migrations.AlterField(
            model_name='labels',
            name='where_are_we_it',
            field=models.CharField(default='', max_length=100, verbose_name="Etichetta 'Dove siamo' (IT)"),
        ),
    ]
