# Generated by Django 6.0.3 on 2026-05-09 11:29

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0038_alter_apartment_max_people_alter_apartment_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePanoramaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Panorama Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (IT)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orine (automatico)')),
                ('welcome_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_images', to='sito.welcomeinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='House Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo immagine (IT)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orine (automatico)')),
                ('welcome_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='sito.welcomeinfo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
