# Generated by Django 6.0.3 on 2026-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0039_homepanoramaimage_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreconfig',
            name='footer_col',
            field=models.CharField(default='bg-gray-800', max_length=100, verbose_name='Colore del footer'),
        ),
    ]
