# Generated by Django 6.0.3 on 2026-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0040_moreconfig_footer_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='book_discount_en',
            field=models.CharField(default='', max_length=100, verbose_name='Messaggio sconto prenotazione (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='book_discount_it',
            field=models.CharField(default='', max_length=100, verbose_name='Messaggio sconto prenotazione (IT)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_min_stay_en',
            field=models.CharField(default='', max_length=100, verbose_name='Form, messaggio soggiorno minimo (EN)'),
        ),
        migrations.AddField(
            model_name='labels',
            name='form_min_stay_it',
            field=models.CharField(default='', max_length=100, verbose_name='Form, messaggio soggiorno minimo (IT)'),
        ),
    ]
