# Generated by Django 6.0.3 on 2026-05-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sito', '0041_labels_book_discount_en_labels_book_discount_it_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='form_min_stay_en',
            field=models.CharField(default='', max_length=1000, verbose_name='Form, messaggio soggiorno minimo (EN)'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='form_min_stay_it',
            field=models.CharField(default='', max_length=1000, verbose_name='Form, messaggio soggiorno minimo (IT)'),
        ),
    ]
